# Generated by Django 3.0.8 on 2020-08-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapinsight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
