# Generated by Django 3.0.8 on 2020-08-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapinsight', '0003_solution_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('some_point', models.CharField(max_length=500)),
                ('what', models.CharField(max_length=500)),
                ('why', models.CharField(max_length=500)),
                ('how', models.CharField(max_length=500)),
                ('keyword', models.CharField(max_length=500)),
            ],
        ),
    ]
