# Generated by Django 3.0.8 on 2020-08-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapinsight', '0006_game_desc_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guideline', models.CharField(max_length=500)),
                ('privacy', models.CharField(max_length=500)),
                ('term', models.CharField(max_length=500)),
            ],
        ),
    ]
