# Generated by Django 3.0.8 on 2020-08-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapinsight', '0008_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('version', models.CharField(max_length=500)),
                ('features', models.CharField(max_length=500)),
                ('start_date', models.CharField(max_length=500)),
                ('end_date', models.CharField(max_length=500)),
            ],
        ),
    ]
