# Generated by Django 3.0.8 on 2020-08-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapinsight', '0014_service_roadmap_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_roadmap',
            name='tag',
            field=models.CharField(default='0', max_length=500),
        ),
    ]
