# Generated by Django 3.0.8 on 2020-08-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapinsight', '0020_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEO_Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('keyword', models.CharField(max_length=500)),
            ],
        ),
    ]
