# Generated by Django 3.0.8 on 2020-08-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapinsight', '0026_service_document_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('link', models.CharField(default='', max_length=500)),
                ('file', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
