# Generated by Django 3.0.8 on 2020-08-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapinsight', '0030_position_map_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='', max_length=500),
        ),
    ]
