# Generated by Django 3.0.8 on 2020-08-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player', models.CharField(max_length=500)),
                ('player_count', models.CharField(max_length=500)),
                ('turn', models.CharField(max_length=500)),
                ('tag', models.CharField(default='0', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('channel_name', models.CharField(max_length=500)),
                ('tag', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='game',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AddField(
            model_name='room',
            name='tag',
            field=models.CharField(default='0', max_length=500),
        ),
    ]
