# Generated by Django 3.0.8 on 2020-08-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='color',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='game',
            name='roll',
            field=models.CharField(default='', max_length=500),
        ),
    ]
