# Generated by Django 3.0.8 on 2020-08-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapinsight', '0002_overview_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution_desc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('principle', models.CharField(max_length=500)),
            ],
        ),
    ]
