# Generated by Django 3.0.8 on 2020-08-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapinsight', '0004_solutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
