# Generated by Django 3.0.8 on 2020-08-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapinsight', '0010_service_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('doc_name', models.CharField(max_length=500)),
                ('doc_link', models.CharField(max_length=500)),
            ],
        ),
    ]
