# Generated by Django 3.0.8 on 2020-08-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapinsight', '0011_service_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Roadmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('step', models.CharField(max_length=500)),
                ('final_step', models.CharField(max_length=500)),
            ],
        ),
    ]
