# Generated by Django 3.0.8 on 2020-08-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapinsight', '0012_service_roadmap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_roadmap',
            name='final_step',
        ),
    ]
