# Generated by Django 3.0.8 on 2020-08-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapinsight', '0021_seo_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('responsible', models.CharField(max_length=500)),
                ('skill', models.CharField(max_length=500)),
                ('benefits', models.CharField(max_length=500)),
            ],
        ),
    ]
