# Generated by Django 3.0.8 on 2020-08-07 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapinsight', '0022_job_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_description',
            old_name='skill',
            new_name='skills',
        ),
    ]
