# Generated by Django 3.0.8 on 2020-08-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapinsight', '0023_auto_20200807_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Portal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
            ],
        ),
    ]
