# Generated by Django 3.0.8 on 2020-08-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapinsight', '0025_contentwriter_ptd'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_document',
            name='tag',
            field=models.CharField(default='', max_length=500),
        ),
    ]
