# Generated by Django 3.0.8 on 2020-08-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapinsight', '0027_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
