# Generated by Django 3.0.8 on 2020-08-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapinsight', '0029_resources_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position_Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=500)),
                ('tag', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=500)),
                ('fname', models.CharField(max_length=500)),
                ('lname', models.CharField(max_length=500)),
                ('position', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('fb', models.CharField(max_length=500)),
                ('twitter', models.CharField(max_length=500)),
                ('insta', models.CharField(max_length=500)),
                ('blog', models.CharField(max_length=500)),
                ('pintrest', models.CharField(max_length=500)),
                ('youtube', models.CharField(max_length=500)),
                ('tag', models.CharField(max_length=500)),
            ],
        ),
    ]
