# Generated by Django 3.0.8 on 2020-08-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('color', models.CharField(max_length=500)),
                ('buy', models.CharField(max_length=500)),
            ],
        ),
    ]
