# Generated by Django 3.0.8 on 2020-08-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='type',
            field=models.CharField(default='2', max_length=500),
        ),
    ]
