# Generated by Django 3.0.8 on 2020-08-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20200819_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='built',
            field=models.CharField(default='', max_length=500),
        ),
    ]
