# Generated by Django 3.0.8 on 2020-08-27 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_game_built'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='built',
            new_name='build',
        ),
    ]
