# Generated by Django 3.0.8 on 2020-09-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20200827_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='build1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='board',
            name='build2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='board',
            name='build3',
            field=models.CharField(default='', max_length=500),
        ),
    ]
