# Generated by Django 3.0.8 on 2020-09-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20200902_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='start',
            field=models.CharField(default='200', max_length=500),
        ),
    ]
