# Generated by Django 3.0.8 on 2020-09-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_game_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='jail',
            field=models.CharField(default='0', max_length=500),
        ),
    ]
