# Generated by Django 3.0.8 on 2020-09-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_game_jail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Random',
            fields=[
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=500)),
                ('quants', models.CharField(max_length=500)),
                ('tag', models.CharField(max_length=500)),
            ],
        ),
    ]
