# Generated by Django 3.0.8 on 2020-09-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_game_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cost_mask',
            field=models.CharField(default='1', max_length=500),
        ),
    ]
