# Generated by Django 2.2.6 on 2020-05-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHOPD', '0005_patient_patient_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_comment',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
