# Generated by Django 2.2.6 on 2020-05-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHOPD', '0006_patient_patient_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_id', models.AutoField(max_length=200, primary_key=True, serialize=False)),
                ('receipt_patient', models.CharField(max_length=200)),
                ('receipt_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
