# Generated by Django 2.2.6 on 2020-05-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHOPD', '0009_auto_20200507_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_status',
            field=models.CharField(default='-1', max_length=10),
        ),
    ]
