# Generated by Django 2.2.6 on 2020-05-14 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DHOPD', '0011_vaccine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_receipt',
        ),
    ]
