# Generated by Django 2.2.6 on 2020-05-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DHOPD', '0018_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
