# Generated by Django 2.2.6 on 2020-05-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHOPD', '0019_delete_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(max_length=200, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=200)),
                ('room_cost', models.CharField(max_length=200)),
                ('room_bed', models.CharField(max_length=10)),
                ('room_bed_occ', models.CharField(max_length=10)),
            ],
        ),
    ]
