# Generated by Django 2.2.6 on 2020-06-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHOPD', '0026_patient_h_patient_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund_h',
            fields=[
                ('refund_id', models.AutoField(max_length=200, primary_key=True, serialize=False)),
                ('refund_patient', models.CharField(max_length=200)),
                ('refund_cost', models.CharField(max_length=200)),
                ('refund_name', models.CharField(max_length=200)),
                ('refund_time', models.DateTimeField(auto_now=True)),
                ('refund_status', models.CharField(default='0', max_length=10)),
            ],
        ),
    ]
