# Generated by Django 2.2.6 on 2020-07-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHOPD', '0027_refund_h'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt_h',
            name='receipt_no',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='receipt_h',
            name='receipt_type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
