# Generated by Django 2.2.6 on 2020-05-22 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictionary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cards',
            new_name='Pict_Cards',
        ),
    ]
