# Generated by Django 2.2.6 on 2020-04-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('pno', models.CharField(max_length=15)),
                ('priority', models.CharField(max_length=2)),
                ('auth', models.CharField(max_length=2)),
            ],
        ),
    ]
