# Generated by Django 2.2.6 on 2020-05-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHOPD', '0004_patient_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_cost',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
