# Generated by Django 2.2.6 on 2020-05-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHOPD', '0013_receipt_receipt_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
