# Generated by Django 2.2.6 on 2020-05-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHOPD', '0016_patient_c_receipt_c'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_h',
            fields=[
                ('service_id', models.AutoField(max_length=200, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=200)),
                ('service_cost', models.CharField(max_length=200)),
                ('service_tag', models.CharField(max_length=200)),
            ],
        ),
    ]
