# Generated by Django 2.2.6 on 2020-05-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHOPD', '0020_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_bed_occ',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
