# Generated by Django 2.2.6 on 2020-05-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('pno', models.CharField(max_length=15)),
                ('priority', models.CharField(max_length=2)),
                ('auth', models.CharField(max_length=2)),
            ],
        ),
    ]
