# Generated by Django 3.0.8 on 2020-08-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='count',
            field=models.CharField(default='0', max_length=500),
        ),
    ]
