# Generated by Django 3.0.8 on 2020-08-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200817_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('color', models.CharField(max_length=500)),
                ('buy', models.CharField(max_length=500)),
                ('rent', models.CharField(max_length=500)),
                ('sell', models.CharField(max_length=500)),
                ('tag', models.CharField(max_length=500)),
            ],
        ),
    ]
