# Generated by Django 2.2.6 on 2020-05-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHOPD', '0003_auto_20200507_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
