# Generated by Django 2.2.6 on 2020-05-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHOPD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_fname', models.CharField(max_length=200)),
                ('patient_mname', models.CharField(max_length=200)),
                ('patient_lname', models.CharField(max_length=200)),
                ('patient_title', models.CharField(max_length=20)),
                ('patient_address', models.CharField(max_length=500)),
                ('patient_town', models.CharField(max_length=200)),
                ('patient_phone', models.CharField(max_length=15)),
                ('patient_services', models.CharField(max_length=500)),
                ('patient_receipt', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=200)),
                ('service_cost', models.CharField(max_length=200)),
            ],
        ),
    ]
