# Generated by Django 2.2.6 on 2020-05-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHOPD', '0003_auto_20200507_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_status',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
