# Generated by Django 2.2.6 on 2020-05-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHOPD', '0010_receipt_receipt_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('vaccine_id', models.AutoField(max_length=200, primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=200)),
            ],
        ),
    ]
