# Generated by Django 2.2.6 on 2020-05-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHOPD', '0012_remove_patient_patient_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_cost',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
