# Generated by Django 2.2.6 on 2020-06-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHOPD', '0025_patient_h_patient_rdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_h',
            name='patient_discount',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
