# Generated by Django 2.2.6 on 2020-07-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHOPD', '0028_auto_20200709_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill_h',
            fields=[
                ('bill_id', models.AutoField(max_length=200, primary_key=True, serialize=False)),
                ('bill_patient', models.CharField(max_length=200)),
                ('bill_cost', models.CharField(max_length=200)),
                ('bill_receipt', models.CharField(max_length=200)),
            ],
        ),
    ]
